package export

import (
	"fmt"
	"sort"
	"strings"
)

// ansibleHost is one guest's rendered inventory entry.
type ansibleHost struct {
	name string
	ip   string // "" when unknown — the host still appears, just without ansible_host
	node string
	tags []string
}

// GenerateAnsibleInventory emits a YAML Ansible inventory grouping guests by
// their Proxmox node, and additionally by guest tag when any guest carries
// one. ansible_host is set only for guests with a known live IP (typically
// via the QEMU/LXC guest agent) — a guest without one is still listed, just
// without connectivity info, since PVE alone can't tell Ansible how to reach
// a guest whose agent isn't installed or hasn't reported yet.
func GenerateAnsibleInventory(connectionName string, guests []Guest) string {
	hosts := make([]ansibleHost, 0, len(guests))
	usedNames := map[string]int{}
	for _, g := range guests {
		if g.Resource.Type != "qemu" && g.Resource.Type != "lxc" {
			continue
		}
		name := g.Resource.Name
		if g.Config != nil && g.Config.Name != "" {
			name = g.Config.Name
		}
		base := slugify(name)
		host := base
		usedNames[base]++
		if n := usedNames[base]; n > 1 {
			// Two guests can share a display name (or slugify to the same
			// one) — keep the inventory valid by disambiguating with the
			// VMID rather than silently dropping one.
			host = fmt.Sprintf("%s-%d", base, g.Resource.VMID)
		}
		hosts = append(hosts, ansibleHost{
			name: host,
			ip:   g.IP,
			node: g.Resource.Node,
			tags: splitTags(g.Resource.Tags),
		})
	}

	sort.Slice(hosts, func(i, j int) bool { return hosts[i].name < hosts[j].name })

	byNode := map[string][]ansibleHost{}
	byTag := map[string][]ansibleHost{}
	var nodeOrder, tagOrder []string
	for _, h := range hosts {
		if _, ok := byNode[h.node]; !ok {
			nodeOrder = append(nodeOrder, h.node)
		}
		byNode[h.node] = append(byNode[h.node], h)
		for _, tag := range h.tags {
			if _, ok := byTag[tag]; !ok {
				tagOrder = append(tagOrder, tag)
			}
			byTag[tag] = append(byTag[tag], h)
		}
	}
	sort.Strings(nodeOrder)
	sort.Strings(tagOrder)

	var b strings.Builder
	fmt.Fprintf(&b, "# Ansible inventory generated by Ferrum from the connection %q.\n", connectionName)
	b.WriteString("# ansible_host is only set for guests with a known live IP (via the QEMU/LXC\n")
	b.WriteString("# guest agent); guests without one are still listed but need ansible_host\n")
	b.WriteString("# added by hand, or the guest agent installed and enabled for a future export\n")
	b.WriteString("# to pick it up.\n\n")

	if len(hosts) == 0 {
		b.WriteString("all:\n  hosts: {}\n")
		return b.String()
	}

	b.WriteString("all:\n  children:\n")
	for _, node := range nodeOrder {
		fmt.Fprintf(&b, "    node_%s:\n      hosts:\n", slugify(node))
		writeHostBlock(&b, byNode[node], "        ")
	}
	for _, tag := range tagOrder {
		fmt.Fprintf(&b, "    tag_%s:\n      hosts:\n", slugify(tag))
		writeHostBlock(&b, byTag[tag], "        ")
	}
	return b.String()
}

func writeHostBlock(b *strings.Builder, hosts []ansibleHost, indent string) {
	for _, h := range hosts {
		if h.ip != "" {
			fmt.Fprintf(b, "%s%s:\n%s  ansible_host: %s\n", indent, h.name, indent, h.ip)
		} else {
			fmt.Fprintf(b, "%s%s: {}\n", indent, h.name)
		}
	}
}
