package export

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// terraformHeader documents what this generator covers and — just as
// importantly — what it doesn't, so a reviewer applying the output knows
// what to check by hand before running `terraform apply`.
const terraformHeader = `# Terraform configuration generated by Ferrum from the connection %q.
# Provider: Telmate/proxmox (https://registry.terraform.io/providers/Telmate/proxmox)
#
# Covers: node placement, cores/sockets/memory, one primary disk, one
# primary network interface, onboot, and tags.
#
# NOT covered — review and add by hand if you need them: additional disks or
# NICs beyond the first, CPU type/flags, BIOS/machine type, cloud-init,
# firewall rules, HA resource config, snapshots, and any storage
# plugin-specific options (e.g. Ceph pool settings). LXC resources also need
# "ostemplate" filled in manually — the running config doesn't retain which
# template a container was created from.
#
# Import existing resources instead of recreating them:
#   terraform import proxmox_vm_qemu.<label> <node>/qemu/<vmid>
#   terraform import proxmox_lxc.<label>      <node>/lxc/<vmid>

`

// GenerateTerraform emits one proxmox_vm_qemu or proxmox_lxc resource block
// per guest, sorted by VMID for a stable, reviewable diff across runs.
func GenerateTerraform(connectionName string, guests []Guest) string {
	var b strings.Builder
	fmt.Fprintf(&b, terraformHeader, connectionName)

	sorted := make([]Guest, len(guests))
	copy(sorted, guests)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Resource.VMID < sorted[j].Resource.VMID })

	for _, g := range sorted {
		switch g.Resource.Type {
		case "qemu":
			b.WriteString(renderQemuResource(g))
			b.WriteString("\n")
		case "lxc":
			b.WriteString(renderLXCResource(g))
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderQemuResource(g Guest) string {
	name := g.Resource.Name
	cores, sockets, memory := 1, 1, 512
	onboot := false
	var disks []struct{ storage, size string }
	var netModel, netBridge, netTag string
	hasDisk, hasNet := false, false

	if g.Config != nil {
		if g.Config.Name != "" {
			name = g.Config.Name
		}
		if g.Config.Cores > 0 {
			cores = g.Config.Cores
		}
		if g.Config.Sockets > 0 {
			sockets = g.Config.Sockets
		}
		if g.Config.Memory > 0 {
			memory = g.Config.Memory
		}
		onboot = g.Config.Onboot != 0
		if storage, size := firstDisk(g.Config.Disks); storage != "" {
			disks = append(disks, struct{ storage, size string }{storage, size})
			hasDisk = true
		}
		if dev, ok := primaryNet(g.Config.NetworkDevices); ok {
			netModel, netBridge, netTag = parseQemuNet(dev.Value)
			hasNet = true
		}
	}

	label := fmt.Sprintf("vm_%d_%s", g.Resource.VMID, slugify(name))

	var b strings.Builder
	fmt.Fprintf(&b, "resource \"proxmox_vm_qemu\" %s {\n", quote(label))
	fmt.Fprintf(&b, "  name        = %s\n", quote(name))
	fmt.Fprintf(&b, "  target_node = %s\n", quote(g.Resource.Node))
	fmt.Fprintf(&b, "  vmid        = %d\n", g.Resource.VMID)
	fmt.Fprintf(&b, "  cores       = %d\n", cores)
	fmt.Fprintf(&b, "  sockets     = %d\n", sockets)
	fmt.Fprintf(&b, "  memory      = %d\n", memory)
	fmt.Fprintf(&b, "  onboot      = %t\n", onboot)
	if g.Resource.Tags != "" {
		fmt.Fprintf(&b, "  tags        = %s\n", quote(g.Resource.Tags))
	}

	b.WriteString("\n")
	if hasDisk {
		d := disks[0]
		b.WriteString("  disk {\n")
		b.WriteString("    slot    = \"scsi0\"\n")
		if d.size != "" {
			fmt.Fprintf(&b, "    size    = %s\n", quote(d.size))
		}
		fmt.Fprintf(&b, "    storage = %s\n", quote(d.storage))
		b.WriteString("    type    = \"disk\"\n")
		b.WriteString("  }\n")
	} else {
		b.WriteString("  # no primary disk detected in the source config — add a disk block manually\n")
	}

	b.WriteString("\n")
	if hasNet {
		b.WriteString("  network {\n")
		fmt.Fprintf(&b, "    model  = %s\n", quote(netModel))
		if netBridge != "" {
			fmt.Fprintf(&b, "    bridge = %s\n", quote(netBridge))
		} else {
			b.WriteString("    bridge = \"vmbr0\" # not set on the source guest — defaulted\n")
		}
		if n, err := strconv.Atoi(netTag); err == nil && netTag != "" {
			fmt.Fprintf(&b, "    tag    = %d\n", n)
		}
		b.WriteString("  }\n")
	} else {
		b.WriteString("  # no network interface detected in the source config — add a network block manually\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderLXCResource(g Guest) string {
	hostname := g.Resource.Name
	cores, memory, swap := 1, 512, 512
	onboot := false
	var rootStorage, rootSize string
	hasRoot := false
	var netName, netBridge, netIP string
	hasNet := false

	if g.Config != nil {
		if g.Config.Name != "" {
			hostname = g.Config.Name
		}
		if g.Config.Cores > 0 {
			cores = g.Config.Cores
		}
		if g.Config.Memory > 0 {
			memory = g.Config.Memory
		}
		onboot = g.Config.Onboot != 0
		if storage, size, ok := rootfsDisk(g.Config.Disks); ok {
			rootStorage, rootSize, hasRoot = storage, size, true
		}
		if dev, ok := primaryNet(g.Config.NetworkDevices); ok {
			netName, netBridge, netIP = parseLXCNet(dev.Value)
			hasNet = true
		}
	}
	if netName == "" {
		netName = "eth0"
	}

	label := fmt.Sprintf("ct_%d_%s", g.Resource.VMID, slugify(hostname))

	var b strings.Builder
	fmt.Fprintf(&b, "resource \"proxmox_lxc\" %s {\n", quote(label))
	fmt.Fprintf(&b, "  hostname     = %s\n", quote(hostname))
	fmt.Fprintf(&b, "  target_node  = %s\n", quote(g.Resource.Node))
	b.WriteString("  ostemplate   = \"local:vztmpl/CHANGE-ME.tar.zst\" # PVE doesn't expose the original template after creation — set this by hand\n")
	fmt.Fprintf(&b, "  cores        = %d\n", cores)
	fmt.Fprintf(&b, "  memory       = %d\n", memory)
	fmt.Fprintf(&b, "  swap         = %d\n", swap)
	fmt.Fprintf(&b, "  unprivileged = true\n")
	fmt.Fprintf(&b, "  onboot       = %t\n", onboot)
	if g.Resource.Tags != "" {
		fmt.Fprintf(&b, "  tags         = %s\n", quote(g.Resource.Tags))
	}

	b.WriteString("\n")
	if hasRoot {
		b.WriteString("  rootfs {\n")
		if rootStorage != "" {
			fmt.Fprintf(&b, "    storage = %s\n", quote(rootStorage))
		}
		if rootSize != "" {
			fmt.Fprintf(&b, "    size    = %s\n", quote(rootSize))
		}
		b.WriteString("  }\n")
	} else {
		b.WriteString("  # no rootfs detected in the source config — add a rootfs block manually\n")
	}

	b.WriteString("\n")
	b.WriteString("  network {\n")
	fmt.Fprintf(&b, "    name   = %s\n", quote(netName))
	if netBridge != "" {
		fmt.Fprintf(&b, "    bridge = %s\n", quote(netBridge))
	} else {
		b.WriteString("    bridge = \"vmbr0\" # not set on the source guest — defaulted\n")
	}
	if netIP != "" {
		fmt.Fprintf(&b, "    ip     = %s\n", quote(netIP))
	}
	if !hasNet {
		b.WriteString("    # no network interface detected in the source config — review before applying\n")
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}
